# Generated by Django 3.2.6 on 2022-06-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220612_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_three',
        ),
    ]
