# Generated by Django 3.2.6 on 2022-06-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='category',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
