# Generated by Django 3.2.6 on 2022-07-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_shoesizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoesizes',
            name='sizes',
        ),
        migrations.AddField(
            model_name='shoesizes',
            name='size',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
