# Generated by Django 3.2.6 on 2022-07-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220706_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoeSizes',
        ),
    ]
