# Generated by Django 3.2.6 on 2022-07-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_shoesizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='lower_limit',
            field=models.DecimalField(decimal_places=2, default=595, max_digits=100),
            preserve_default=False,
        ),
    ]
