# Generated by Django 3.2.6 on 2022-07-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_lower_limit_coupon_down_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelledAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='isCancelled',
            field=models.BooleanField(default=False),
        ),
    ]
