# Generated by Django 3.2.6 on 2022-09-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20220711_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='used_by',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.IntegerField(default=0, max_length=15),
        ),
    ]
